server:
  port: 9031

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: sca-nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

